# Generated by Django 5.0.6 on 2024-05-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_games", models.IntegerField()),
                ("max_games", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s1", models.IntegerField()),
                ("s2", models.IntegerField()),
                ("d1", models.IntegerField()),
                ("d2", models.IntegerField()),
                ("d3", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s", models.IntegerField()),
                ("d", models.IntegerField()),
                ("available_matches", models.ManyToManyField(to="teams.match")),
                ("doubles_partners", models.ManyToManyField(to="teams.player")),
            ],
        ),
    ]
