# Generated by Django 5.0.6 on 2024-05-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Defaults",
            new_name="Default",
        ),
    ]
