# Generated by Django 5.0.6 on 2024-05-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_rename_defaults_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="opposing_team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
            preserve_default=False,
        ),
    ]
