# Generated by Django 5.0.6 on 2024-05-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_match_name_match_opposing_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
