# Generated by Django 5.0.6 on 2024-05-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_match_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="max_single_games",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="player",
            name="min_double_games",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="opposing_team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="d",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="player",
            name="s",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="d1",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="d2",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="d3",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="s1",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="team",
            name="s2",
            field=models.IntegerField(default=6),
        ),
    ]
