# Generated by Django 5.0.6 on 2024-05-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_remove_team_match_doublesgame_singlesgame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublesgame",
            name="player_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_one",
                to="teams.player",
            ),
        ),
        migrations.AlterField(
            model_name="doublesgame",
            name="player_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_two",
                to="teams.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="singlesgame",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.player",
            ),
        ),
    ]
