# Generated by Django 5.0.6 on 2024-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_delete_pair"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublesgame",
            name="manually_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="singlesgame",
            name="manually_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
